AlpineAura/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('basket.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import UserLoginForm, ResetPasswordForm, ResetPasswordConfirmForm
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html', form_class=UserLoginForm),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='user/reset-password.html',
                                                                 success_url='reset-password-email-confirm',
                                                                 email_template_name='user/reset-password-email.html',
                                                                 form_class=ResetPasswordForm),
         name='reset_password'),
    path('reset-password-confirm/<slug:uidb64>/<slug:token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='user/reset-password-confirm.html',
                                                     success_url='/account/reset-password-email-complete',
                                                     form_class=ResetPasswordConfirmForm),
         name='reset_password_confirm'),
    path('reset-password/reset-password-email-confirm', TemplateView.as_view(template_name='user/reset-status.html'),
         name='reset_password_done'),
    path('reset-password-email-complete', TemplateView.as_view(template_name='user/reset-status.html'),
         name='reset_password_complete'),

    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="user/confirm-delete.html"),
         name='delete_confirmation'),
    path('addresses/', views.view_address, name='addresses'),
    path('add-address/', views.add_address, name='add_address'),
    path('addresses/edit/<slug:id>/', views.edit_address, name='edit_address'),
    path('addresses/delete/<slug:id>/', views.delete_address, name='delete_address'),
    path('addresses/set-default/<slug:id>/', views.set_default, name='set_default'),

    path('wishlist/add-item-to-wishlist/<int:id>', views.add_item_to_wishlist, name='add_item_to_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/delete_item_to_wishlist/<int:id>', views.delete_item_to_wishlist, name='delete_item_to_wishlist'),
    path('orders/', views.user_orders, name='user_orders')
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update')
]

payment/urls.py
from django.urls import path

from payment import views

app_name = 'payment'

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('orderplaced/', views.order_placed, name='order_placed'),
    path('error/', views.Error.as_view(), name='error'),
    path('webhook/', views.stripe_webhook),
    path("delivery-choices", views.delivery_choices, name="delivery_choices"),
    path("cart-update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
    path("delivery-address/", views.delivery_address, name="delivery_address"),
    path("payment-selection/", views.payment_selection, name="payment_selection"),
    path("payment-complete/", views.payment_complete, name="payment_complete"),
]

store/urls.py
from  django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:category_slug>/<slug:slug>', views.product_page, name='product'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('about-us/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('size-guides/', views.size_guides, name='size guides'),
    path('return-policy/', views.return_policy, name='return policy'),
    path('privacy-policy/', views.privacy_policy, name='privacy policy'),
    path('terms-of-service/', views.terms_of_service, name='terms of service'),
    ]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.

class Category(MPTTModel):
    name = models.CharField(verbose_name="Category Name", help_text="Required and unique", max_length=255, unique=True)
    slug = models.SlugField(verbose_name="Category Safe Url", max_length=255, unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    is_active = models.BooleanField(default=True)
    icon = models.ImageField(verbose_name="Icon", help_text="Upload an icon for the category", upload_to="category_icons/", null=True, blank=True)
    category_image = models.ImageField(verbose_name="Category Image", help_text="Upload an image for the category", upload_to="category_images/", null=True, blank=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class ProductType(models.Model):
    name = models.CharField(verbose_name="Product Name", help_text="Required and unique", max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Product Type"
        verbose_name_plural = "Products Types"

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name="Name", help_text="Required and unique", max_length=255)

    class Meta:
        verbose_name = "Product Specification"
        verbose_name_plural = "Product Specifications"

    def __str__(self):
        return self.name


class Product(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)

    product_title = models.CharField(verbose_name="Product Title Name", help_text="Required and unique", max_length=255,
                                     unique=True)
    description = models.TextField(verbose_name="Description", help_text="Not Required", blank=True)
    long_description = models.TextField(verbose_name="Long Description", help_text="Not Required", blank=True)
    brand = models.CharField(verbose_name="Brand name", max_length=255, blank=True)
    sku = models.CharField(verbose_name="SKU", max_length=255, blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(verbose_name="Regular Price", help_text="Maximum 999.99", max_digits=5,
                                        decimal_places=2, error_messages={
            "name": {"max_length": "The price must be between 0 and 999.99 €"}})
    discount_price = models.DecimalField(verbose_name="Discount Price", help_text="Maximum 999.99", max_digits=5,
                                         decimal_places=2, error_messages={
            "name": {"max_length": "The price must be between 0 and 999.99 €"}})
    is_active = models.DateTimeField(verbose_name="Created at", auto_now_add=True, editable=False)
    created_at = models.DateTimeField("Created at", auto_now_add=True, editable=False)
    updated_at = models.DateTimeField("Updated at", auto_now=True)
    user_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def get_absolute_url(self):
        return reverse("store:product", args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_title


class ProductSpecificationValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(verbose_name="Value", help_text="Product specification value (maximum of 255 words",
                             max_length=255)

    class Meta:
        verbose_name = "Product Specification Value"
        verbose_name_plural = "Product Specification Values"

    def __str__(self):
        return self.value


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(verbose_name="image", help_text="Upload a product image", upload_to="images/",
                              default='images/default.png')
    alt_text = models.CharField(verbose_name="Alternative Text", help_text="Please add alternative text",
                                max_length=255, null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    is_active = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        verbose_name = "Product Image"
        verbose_name_plural = "Product Images"

store/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404

from AlpineAura.settings import RECIPIENT_LIST
from .models import Category, Product, ProductSpecificationValue


# Create your views here.

def home(request):
    products = Product.objects.all()
    latest_products = Product.objects.order_by('-created_at')[:8]
    latest_product_ids = latest_products.values_list('id', flat=True)

    random_products = Product.objects.exclude(id__in=list(latest_product_ids)).order_by('?')[:4]

    return render(request, 'store/home.html',
                  {'products': products, 'latest_products': latest_products, 'random_products': random_products})


def product_page(request, category_slug, slug):
    category = get_object_or_404(Category, slug=category_slug)
    product = get_object_or_404(Product, slug=slug, category=category)
    product_specifications = ProductSpecificationValue.objects.filter(product=product)

    related_products = Product.objects.filter(category=category).exclude(id=product.id).order_by('-created_at')[:4]

    return render(request, 'store/product.html', {'product': product,
                                                  'product_specifications': product_specifications,
                                                  'related_products': related_products
                                                  })


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(
        category__in=category.get_descendants(include_self=True)
    )
    return render(request, "store/category.html", {"category": category, "products": products})


def about(request):
    return render(request, 'store/about.html')


def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        send_mail(
            subject=f"{subject} from {name}",
            message=message,
            from_email=email,
            recipient_list=RECIPIENT_LIST
        )

        messages.success(request, "Your message has been sent successfully!")

        return render(request, 'store/contact.html')
    else:
        return render(request, 'store/contact.html')


def return_policy(request):
    return render(request, 'store/return-policy.html')


def size_guides(request):
    return render(request, 'store/size-guides.html')


def privacy_policy(request):
    return render(request, 'store/privacy-policy.html')


def terms_of_service(request):
    return render(request, 'store/terms-of-service.html')


def shop(request):
    categories = Category.objects.all()
    return render(request, 'store/shop.html', {'categories': categories})

templates/store/article.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<h3>hay</h3>
{% endblock content %}

templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto mt-10">
    <div class="shadow-lg my-10">
        <!-- Shopping Cart Section -->
        <div class="bg-white px-10 py-10">
            <div class="flex justify-between border-b pb-8">
                <h1 class="font-semibold text-2xl">Shopping Cart</h1>
                <h2 id="items-count" class="font-semibold text-2xl">
                    {% with total_qty=Cart|length %}
                        {% if total_qty > 0 %}{{ total_qty }}{% else %}0{% endif %}
                    {% endwith %} Items
                </h2>
            </div>

            {% for item in Cart %} {% with product=item.product %}
            <div data-index="{{ product.id }}" class="product-item">
                <div class="flex mt-5 mb-5 items-center">
                    <div class="w-2/5">
                        {% for image in product.product_image.all %} {% if image.is_featured %}
                        <img src="{{ image.image.url }}" alt="{{ image.image.alt_text }}" class="w-20 h-20">
                        {% endif %} {% endfor %}
                    </div>
                    <div class="w-2/5 flex flex-col justify-between ml-4">
                        <span class="font-bold text-sm">{{ product.product_title }}</span>
                        <span class="text-xs">
                            {% if product.discount_price %}
                            <span class="text-red-500"> {{ product.discount_price }} € </span>
                            <span class="text-gray-500 line-through"> {{ product.regular_price }} € </span> 
                            {% else %}
                            <span class="text-black"> {{ product.regular_price }} € </span> 
                            {% endif %}
                        </span>

                        <div class="flex items-center mt-2">
                            <button type="button" data-index="{{ product.id }}" data-url="{% url 'cart:cart_update' %}" data-csrf-token="{{ csrf_token }}" class="decrease-qty text-gray-500 focus:outline-none focus:text-gray-600 update-button">
                                <img src="{% static 'icons/remove.svg' %}">
                            </button>
                            <input type="number" value="{{ item.qty }}" class="mx-2 border text-center w-24" min="1">
                            <button type="button" data-index="{{ product.id }}" data-url="{% url 'cart:cart_update' %}" data-csrf-token="{{ csrf_token }}" class="increase-qty text-gray-500 focus:outline-none focus:text-gray-600 update-button">
                                <img src="{% static 'icons/add.svg' %}">
                            </button>
                        </div>
                    </div>

                    <div class="w-1/5 flex justify-end items-center">
                        <button type="button" id="delete-button" data-url="{% url 'cart:cart_delete' %}" data-csrf-token="{{ csrf_token }}" data-index="{{ product.id }}" class="text-sm font-semibold flex items-center delete-button">
                            <img src="{% static 'icons/close.svg' %}">
                        </button>
                    </div>
                </div>
                <hr class="my-5">
            </div>
            {% endwith %} {% endfor %}
            <a href="#" class="flex items-center font-semibold text-primary text-sm mt-10">
                <img src="{% static 'icons/arrow_back.svg' %}">Back to shop
            </a>
        </div>

        <!-- Total Cost Section -->
        <div class="mt-8 w-full bg-white px-10 py-6">
            <div class="flex justify-between border-b pb-4">
                <h2 class="font-semibold text-xl">Total Cost</h2>
                <h2 id="total_price" class="font-semibold text-xl">€{{ Cart.get_subtotal_price }}</h2>
            </div>
            <a href="{% url 'payment:delivery_choices' %}"
               class="block mt-4 w-full py-3 px-4 text-center text-white bg-primary border border-primary rounded-md hover:bg-transparent hover:text-primary transition font-medium">
                Delivery Choices
            </a>
        </div>
    </div>
</div>
<script src="{% static 'js/cart.js' %}"></script>
{% endblock content %}

templates/store/contact.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

    <div class="container py-4 flex items-center gap-3">
        <a href="{% url 'store:home' %}" class="text-primary text-base">
            <img class="" src="{% static 'icons/home.svg' %}">
        </a>
        <span class="text-sm text-gray-400">
            <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z"/></svg>
        </span>
        <p class="text-gray-600 font-medium">Contact</p>
    </div>
    
    <!-- django messages -->
    <div id="message" class="container mx-auto my-4 px-4">
        {% if messages %}
            {% for message in messages %}
                <div class="flex items-center bg-blue-100 border-t-4 border-blue-500 rounded-b text-blue-900 px-4 py-3 shadow-md"
                     role="alert">
                    <img class="p-1" src="{% static 'icons/info.svg' %}">
                    <div>
                        <p class="font-bold">Notification</p>
                        <p class="text-sm">{{ message }}</p>
                    </div>
                    <div class="ml-auto pl-4">
                        <button class="close-button text-sm text-blue-500 focus:outline-none"
                                onclick="this.parentElement.parentElement.style.display='none';">
                            <img src="{% static 'icons/close.svg' %}">
                        </button>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <!-- end django messages -->

    <div class="container mx-auto p-5">
        <h1 class="text-2xl font-bold text-center mb-4">Contact Us</h1>
        <p class="text-center mb-8">At AlpineAura, we're here to help you embark on your next outdoor adventure with confidence. Whether you have a question about our products, need assistance with your order, or just want to share your mountain tales, we're all ears.</p>

        <div class="bg-white shadow-md rounded p-6">
            <h2 class="text-xl font-semibold mb-4">Get in Touch</h2>
            <p class="mb-4">Feel free to reach out to us through the following channels:</p>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                <div>
                    <h3 class="font-semibold">Email:</h3>
                    <p>support@alpineaura.com</p>
                    <p>(For customer support, order queries, and general inquiries)</p>
                </div>
                <div>
                    <h3 class="font-semibold">Phone:</h3>
                    <p>+1 (800) 123-4567</p>
                    <p>(Monday to Friday: 9 AM - 6 PM EST)</p>
                </div>
            </div>

            <div class="mb-6">
                <h3 class="font-semibold">Headquarters:</h3>
                <p>AlpineAura Inc.,</p>
                <p>123 Mountain Trail Lane,</p>
                <p>Aspen, CO 81611, USA</p>
            </div>

            <div class="mb-6">
                <h3 class="font-semibold">Follow Us:</h3>
                <p>Stay connected and follow our journey on social media for the latest updates, offers, and outdoor inspiration.</p>
                <div class="flex space-x-4 mt-2">
                    <a href="#" class="text-blue-600">[Facebook Icon]</a>
                    <a href="#" class="text-pink-600">[Instagram Icon]</a>
                    <a href="#" class="text-blue-400">[Twitter Icon]</a>
                    <a href="#" class="text-red-600">[YouTube Icon]</a>
                </div>
            </div>

            <form action="{% url 'store:contact' %}" method="post">
                {% csrf_token %}
                <h3 class="font-semibold mb-4">Send Us a Message</h3>
                <div class="mb-4">
                    <label for="name" class="block mb-2">Name</label>
                    <input type="text" id="name" name="name" class="w-full p-2 border border-gray-300 rounded">
                </div>
                <div class="mb-4">
                    <label for="email" class="block mb-2">Email</label>
                    <input type="email" id="email" name="email" class="w-full p-2 border border-gray-300 rounded">
                </div>
                <div class="mb-4">
                    <label for="subject" class="block mb-2">Subject</label>
                    <input type="text" id="subject" name="subject" class="w-full p-2 border border-gray-300 rounded">
                </div>
                <div class="mb-6">
                    <label for="message" class="block mb-2">Message</label>
                    <textarea id="message" name="message" rows="4" class="w-full p-2 border border-gray-300 rounded"></textarea>
                </div>
                <button type="submit" class="bg-primary text-white px-4 py-2 rounded hover:bg-primary-dark">Submit</button>
            </form>

            <div class="my-8">
            <h3 class="font-semibold mb-4">Map and Directions</h3>
            <iframe width="425" height="350" src="https://www.openstreetmap.org/export/embed.html?bbox=8.160095214843752%2C51.857411127607996%2C8.709411621093752%2C52.17224727394878&amp;layer=mapnik" style="border: 1px solid black"></iframe><br/><small><a href="https://www.openstreetmap.org/#map=11/52.0151/8.4348">View Larger Map</a></small>
        </div>
        </div>
    </div>
{% endblock content %}

templates/store/main.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}AlpineAura - Your Outdoor Ecommerce Shop{% endblock title %}</title>

    <link rel="shortcut icon" href="{% static 'img/AlpineAura.ico' %}" type="image/x-icon">

    {% tailwind_css %}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap"
        rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body>
<!-- header -->
    <header class="py-4 shadow-sm bg-white">
        <div class="container flex items-center justify-between">
            <a href="{% url "store:home" %}">
                <img src="{% static 'img/AlpineAura_Logo.png' %}" alt="Logo" class="w-64 md:w-48 lg:w-40">
            </a>

            <div class="flex items-center space-x-4">
                <a href="{% url 'account:wishlist' %}" class="flex flex-col items-center text-center text-gray-700 hover:text-primary transition relative">
                    <div class="text-2xl">
                        <img src="{% static 'icons/favorite.svg' %}" alt="Wishlist Icon">
                    </div>
                    <div class="text-xs leading-3">Wishlist</div>
                </a>

                <a href="{% url 'cart:cart_summary' %}" class="flex flex-col items-center text-center text-gray-700 hover:text-primary transition relative">
                    <div class="text-2xl">
                        <img src="{% static 'icons/shopping_cart.svg' %}" alt="Shopping Cart Icon">
                    </div>
                    <div class="text-xs leading-3">Cart</div>
                    <div id="cart-qty" class="absolute right-0 -top-1 w-5 h-5 rounded-full flex items-center justify-center bg-primary text-white text-xs">
                        {% with total_qty=Cart|length %}
                            {% if total_qty > 0 %}
                                {{ total_qty }}
                            {% else %}
                                0
                            {% endif %}
                        {% endwith %}
                    </div>
                </a>
                <a href="{% url 'account:dashboard' %}" class="flex flex-col items-center text-center text-gray-700 hover:text-primary transition relative">
                    <div class="text-2xl">
                        <img src="{% static 'icons/person.svg' %}" alt="Account Picture">
                    </div>
                    <div class="text-xs leading-3">Account</div>
                </a>
            </div>
        </div>
    </header>
    <!-- ./header -->

    <!-- navbar -->
    <nav class="bg-gray-800">
        <div class="container flex">
            <div class="px-8 py-4 bg-primary md:flex items-center cursor-pointer relative group hidden">
                <span class="text-white">
                    <img src="{% static 'icons/menu.svg' %}">
                </span>
                <span class="capitalize ml-2 text-white items-center">All Categories</span>

                <!-- dropdown -->
                <div
                    class="absolute w-full left-0 top-full bg-white shadow-md py-3 divide-y divide-gray-300 divide-dashed opacity-0 group-hover:opacity-100 transition duration-300 invisible group-hover:visible">
                    
                    {% for c in categories %}
                    <a href="{{ c.get_absolute_url }}" class="flex items-center px-6 py-3 hover:bg-gray-100 transition">
                    {% if c.icon %}
                        <img src="{{ c.icon.url }}" alt="Icon for {{ c.name }}" class="w-5 h-5 object-contain">
                    {% endif %}
                        <span class="ml-6 text-gray-600 text-sm">{{ c.name|title }}</span>
                    </a>
                    {% endfor %}
                
                </div>
            </div>

            <div class="flex items-center justify-between flex-grow md:pl-12 py-5">
                <div class="flex items-center space-x-6 capitalize">
                    <a href="{% url 'store:home' %}" class="text-gray-200 hover:text-white transition">Home</a>
                    <a href="{% url 'store:shop' %}" class="text-gray-200 hover:text-white transition">Shop</a>
                    <a href="{% url 'store:about' %}" class="text-gray-200 hover:text-white transition">About us</a>
                    <a href="{% url 'store:contact' %}" class="text-gray-200 hover:text-white transition">Contact us</a>
                </div>
                {% if user.is_authenticated %}
                <a href="{% url 'account:logout' %}" class="text-red-500 hover:text-white transition">Logout</a>
                {% else %}
                    <a href="{% url 'account:login' %}" class="text-gray-200 hover:text-white transition">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <!-- ./navbar -->
<main>
    {% block content %}
    {% endblock %}
</main>
<!-- footer -->
<footer class="bg-white pt-16 pb-12 border-t border-gray-100">
    <div class="container mx-auto px-6">
        <!-- Grid for all sizes, starting with single column for mobile -->
        <div class="grid grid-cols-1 gap-4 mt-4 md:grid-cols-2 lg:grid-cols-4">
            <!-- Logo and description -->
            <div class="space-y-4 mb-4 md:mb-0">
                <img src="{% static 'img/AlpineAura_Logo.png' %}" alt="logo" class="w-48">
                <p class="text-gray-500">
                    AlpineAura is dedicated to providing premium outdoor gear for hiking enthusiasts. Our mission is to equip adventurers with high-quality, durable, and sustainable products that enhance their outdoor experiences.
                </p>
                <div class="flex space-x-5">
                    <!-- Social media links -->
                    <!-- Add your social media links here -->
                </div>
            </div>

            <!-- Customer Information -->
            <div class="mb-4 md:mb-0">
                <h3 class="text-sm font-semibold text-gray-400 uppercase tracking-wider">Customer Information</h3>
                <div class="mt-4 space-y-4">
                    <a href="{% url 'store:about' %}" class="text-base text-gray-500 hover:text-gray-900 block">About Us</a>
                    <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">Shop</a>
                    <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">Blog</a>
                    <a href="{% url 'store:contact' %}" class="text-base text-gray-500 hover:text-gray-900 block">Contact Us</a>
                </div>
            </div>

            <!-- Resources & Policies -->
            <div class="mb-4 md:mb-0">
                <h3 class="text-sm font-semibold text-gray-400 uppercase tracking-wider">Resources & Policies</h3>
                <div class="mt-4 space-y-4">
                    <a href="{% url 'store:size guides' %}" class="text-base text-gray-500 hover:text-gray-900 block">Size Guides</a>
                    <a href="{% url 'store:return policy' %}" class="text-base text-gray-500 hover:text-gray-900 block">Shipping and Returns Policy</a>
                    <a href="{% url 'store:privacy policy' %}" class="text-base text-gray-500 hover:text-gray-900 block">Privacy Policy</a>
                    <a href="{% url 'store:terms of service' %}" class="text-base text-gray-500 hover:text-gray-900 block">Terms of Service</a>
                </div>
            </div>

            <!-- Add additional sections or content here as needed -->
        </div>
    </div>
</footer>
<!-- ./footer -->

<!-- copyright -->
<div class="bg-gray-800 py-4">
    <div class="container mx-auto flex flex-col items-center justify-between px-6 text-center md:flex-row md:text-left">
        <p class="text-white mb-4 md:mb-0">&copy; AlpineAura - All Rights Reserved</p>
    </div>
</div>
<!-- ./copyright -->

</body>
</html>